n = input("Escreve algo:")
print("O tipo primitivo daquilo que escreveste é:", type(n))
print("Escreveste só letras:", n.isalpha())
print("Escreveste só números:", n.isnumeric())
print("Escreveste letras e/ou números:", n.isalnum())
print("Escreveste um espaço:", n.isspace())
print("Escreveste só letras maiúsculas:", n.isupper())
print("Escreveste só letras minúsculas:", n.islower())
print("Escreveste uma palavra que começa por uma letra maúscula:", n.istitle())
